### ISSUE TITLE
Search Result and Store Profile screen: Background image is messed up

### ISSUE THREAD

**Issue by cnasenberg** [smallbusinesshero/dds-wvv-frontend#92]
The background image for both search result and store profile screen has too high contrast and is too far zoomed in. This might be related to the resolution of the screen, maybe some responsiveness issue? 

Acceptance Criteria 
- Background image has standard resolution at all times, even if only a part of it is visible.

**Comment by haugthom** [comment]
Hi @cnasenberg ,

i checked this issue. It happens if you trigger the search and the full page gets longer because of the search results. At the moment the background image try to cover the full page background. And because the site so long with the search results it zooms / scales up in.

We can`t implement a solution with the current image. Either get rid of the image completely or we have a image at the top which fades out at the bottom.

Best
Thomas

**Comment by cnasenberg** [comment]
Hi @haugthom, 
Please do any of the two, whatever looks best with optimal readability. 
Thank you!

**Comment by jonathan-wiens** [comment]
I think this can be closed with the new design? See http://dev-dds-wvv-frontend.herokuapp.com

**Comment by haugthom** [comment]
closed because new design is implemented and will be deployed soon.
